language: cpp
compiler:
  - gcc
sudo: required
before_install:
  - sudo apt-get update -qq
  - wget https://www.libsdl.org/release/SDL2-2.0.10.tar.gz && tar -xzf SDL2-2.0.10.tar.gz
  - pushd SDL2-2.0.10 && ./configure && make && sudo make install && popd
  - wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz && tar -xzf SDL2_image-2.0.5.tar.gz
  - pushd SDL2_image-2.0.5 && ./configure && make && sudo make install && popd
  - wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz && tar -xzf SDL2_ttf-2.0.15.tar.gz
  - pushd SDL2_ttf-2.0.15 && ./configure && make && sudo make install && popd 
script: rm -rf .scon* && scons -c && scons
