image: Visual Studio 2017
platform: x64

install:
  - set MSYSTEM=MINGW64
  - set COMPILER=msys2
  - set MSYS2_ARCH=x86_64
  - set MSYS2_DIR=msys64
  - set PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%
  - bash -lc "pacman -S --needed --noconfirm make cmake scons"
  - bash -lc "pacman -Syu --noconfirm"
  - bash -lc "pacman --noconfirm -Sy mingw-w64-x86_64-toolchain mingw-w64-x86_64-libc++ mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-SDL2_ttf" 
  
build_script:
  - bash -lc "which ld" 
  - bash -lc "which pkg-config"
  - bash -lc "which -a pkg-config"
  - bash -lc "export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/mingw64/lib/pkgconfig; pkg-config --cflags --libs sdl2"
  - bash -lc "export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/mingw64/lib/pkgconfig; cd $APPVEYOR_BUILD_FOLDER; export CC=gcc; export CXX=g++; scons prefix=/mingw64" 
 
matrix:
  fast_finish: true
